### ISSUE TITLE
Japanese token file is named according to a country code

### ISSUE THREAD

**Issue by 1ec5** [mapbox/geocoder-abbreviations#36]
[jp.json](https://github.com/mapbox/geocoder-abbreviations/blob/master/tokens/jp.json) should be renamed ja.json. `JP` is the ISO country code; `ja` is the ISO language code.

/cc @ingalls @boblannon

**Comment by boblannon** [comment]
oof, thanks. not the first time this has happened.  I'll open a pull, and we can do integration tests elsewhere to be sure there aren't negative consequences.

**Comment by bookest** [comment]
Looks like this was fixed in #45.
