### ISSUE TITLE
Who are you r41? ...and where did you come from?

### ISSUE THREAD

**Issue by miccolis** [mapbox/geocoder-abbreviations#40]
In our english numeric abbreviations "four" becomes "r41" https://github.com/mapbox/geocoder-abbreviations/blob/ea6f89030965ea3e04ea9022cb471f0f6df2735d/tokens/en.json#L16

r41 appears to have made their first appearance back in https://github.com/mapbox/geocoder-abbreviations/commit/ccf754a35b7b1304402fcf590b9f268f65479dde :wave: @ingalls

**Comment by ingalls** [comment]
@miccolis most of these were pulled from postal lists or compiled by hand, I would suspect that this is a typo that should be fixed up.

**Comment by ingalls** [comment]
Fixed in `v2.3.1`
